import { Link, useNavigate, useParams } from "react-router-dom";
import { PageHeader } from "@/components/layout/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { systemAlerts } from "@/data/mock";
import { toast } from "sonner";
export default function AlertDetail(){const {id}=useParams(); const nav=useNavigate(); const a=systemAlerts.find(x=>x.id===id) || systemAlerts[0]; return <><PageHeader title={a.title} subtitle="Alert detail and fallback resolution center" actions={<><Button variant="outline" onClick={()=>toast.success("Alert resolved")}>Resolve alert</Button><Button onClick={()=>a.route?nav(a.route):toast.info("No route available")}>Open destination</Button></>}/><div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-base">Full alert context</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p>{a.description}</p><div className="grid gap-2 md:grid-cols-2"><Row label="Type" value={a.type}/><Row label="Entity" value={`${a.entityType}: ${a.entityId}`}/><Row label="Timestamp" value={a.timestamp}/><Row label="Severity" value={<Badge className="capitalize">{a.severity}</Badge>}/></div><div className="rounded-md bg-muted/50 p-3"><p className="font-medium">Recommended action</p><p className="mt-1 text-muted-foreground">{a.recommendedAction}</p></div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Manual actions</CardTitle></CardHeader><CardContent className="space-y-2"><Button className="w-full" onClick={()=>nav(a.route || "/notifications")}>View related entity</Button><Button className="w-full" variant="outline" onClick={()=>toast.success("Alert dismissed")}>Dismiss alert</Button><Button className="w-full" variant="outline" onClick={()=>toast.success("Task assigned")}>Assign task</Button><Button className="w-full" variant="outline" asChild><Link to="/programs">View related program</Link></Button></CardContent></Card></div></>}
function Row({label,value}:any){return <div className="flex justify-between border-b pb-2"><span className="text-muted-foreground">{label}</span><span className="font-medium text-right">{value}</span></div>}
