import { useState } from "react";
import { useParams } from "react-router-dom";
import { PageHeader } from "@/components/layout/PageHeader";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { faculty, courses } from "@/data/mock";
import { toast } from "sonner";
export default function FacultyDetail(){const {id}=useParams(); const [open,setOpen]=useState(false); const f=faculty.find(x=>x.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")===id)||faculty[3]; const assigned=courses.filter(c=>c.faculty===f.name); return <><PageHeader title={f.name} subtitle={f.title} actions={<Button onClick={()=>setOpen(true)}>Reassign Course</Button>}/><div className="grid gap-4 lg:grid-cols-3"><Card><CardContent className="p-4"><div className="flex items-center gap-3"><Avatar className="h-14 w-14"><AvatarFallback className="bg-primary/10 text-primary">{f.name.split(" ").map(n=>n[0]).join("").slice(0,2)}</AvatarFallback></Avatar><div><p className="font-semibold">{f.email}</p><p className="text-sm text-muted-foreground">{f.expertise.join(", ")}</p></div></div><div className="mt-4"><div className="flex justify-between text-sm"><span>Capacity</span><span>{f.workload}%</span></div><Progress value={f.workload} className="mt-2"/></div></CardContent></Card><Card className="lg:col-span-2"><CardHeader><CardTitle className="text-base">Assigned courses</CardTitle></CardHeader><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Course</TableHead><TableHead>Modules</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{assigned.map(c=><TableRow key={c.id}><TableCell>{c.title}</TableCell><TableCell>{c.modules}</TableCell><TableCell className="capitalize">{c.status}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card><Card className="lg:col-span-3"><CardHeader><CardTitle className="text-base">Workload distribution</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-4">{["Teaching","Grading","Mentoring","Content"].map((x,i)=><div key={x} className="rounded-md border p-3"><p className="text-sm">{x}</p><Progress value={[35,22,18,13][i]} className="mt-2"/></div>)}</CardContent></Card></div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Reassign Course</DialogTitle></DialogHeader><Select><SelectTrigger><SelectValue placeholder="Select course"/></SelectTrigger><SelectContent>{assigned.map(c=><SelectItem key={c.id} value={c.id}>{c.title}</SelectItem>)}</SelectContent></Select><Select><SelectTrigger><SelectValue placeholder="Select new faculty"/></SelectTrigger><SelectContent>{faculty.filter(x=>x.id!==f.id).map(x=><SelectItem key={x.id} value={x.id}>{x.name}</SelectItem>)}</SelectContent></Select><DialogFooter><Button onClick={()=>{toast.success("Course transfer confirmed");setOpen(false)}}>Confirm transfer</Button></DialogFooter></DialogContent></Dialog></>}
